- id: '1601337858401'
  alias: send iphone notification when snapshots are stale
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.snapshots_stale
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_victor_s_iphone_7
    data:
      title: Snapshots are Stale
      message: Please visit the 'Home Assistant Google Drive Backup' add-on status
        page for details.
  mode: single
- id: '1601830843021'
  alias: send notification when ha is shutting down
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.mobile_app_victor_s_iphone_7
    data:
      title: Home assistant is shutting down
      message: Home assistant is shutting down
  mode: single
- id: '1601921325598'
  alias: Dressing light on
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: a58837be073111ebb435935160464cbc
    entity_id: binary_sensor.dressing_door_contact
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: a3d53b2201be11ebb038ed0bd676b297
    entity_id: light.56301471b4e62d5675cb
    domain: light
  mode: single
- id: '1601921352335'
  alias: Dressing light off
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: a58837be073111ebb435935160464cbc
    entity_id: binary_sensor.dressing_door_contact
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: a3d53b2201be11ebb038ed0bd676b297
    entity_id: light.56301471b4e62d5675cb
    domain: light
  mode: single
- id: '1601921511171'
  alias: Bedroom light Aurelie
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: c2de4be2067211eb868951b899c5ca20
    type: action
    subtype: single_left
    discovery_id: 0x00158d000421f159 action_single_left
  - platform: device
    domain: mqtt
    device_id: c2de4be2067211eb868951b899c5ca20
    type: click
    subtype: both
    discovery_id: 0x00158d000421f159 click_both
  condition: []
  action:
  - type: toggle
    device_id: a3e76e0b01be11eba70927d7cec6c237
    entity_id: light.5058740184f3ebd05dfd
    domain: light
  mode: single
- id: '1601921547978'
  alias: Bedroom light Victor
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: c2de4be2067211eb868951b899c5ca20
    type: action
    subtype: single_right
    discovery_id: 0x00158d000421f159 action_single_right
  - platform: device
    domain: mqtt
    device_id: c2de4be2067211eb868951b899c5ca20
    type: click
    subtype: both
    discovery_id: 0x00158d000421f159 click_both
  condition: []
  action:
  - type: toggle
    device_id: a3da4cdd01be11eb925abbb96d1f2bb5
    entity_id: light.5058740184f3ebd0613c
    domain: light
  mode: single
- id: '1601921835170'
  alias: '[Office] light strip decrease'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fb5acc2a066f11eb8782ab347bdf11a0
    type: action
    subtype: rotate_left
    discovery_id: 0x00158d00042d6e36 action_rotate_left
  condition: []
  action:
  - type: brightness_decrease
    device_id: a3ebeffb01be11ebaec2cbdc41234aa6
    entity_id: light.light_strip
    domain: light
  mode: single
- id: '1601921944625'
  alias: '[Office] Light strip increase'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fb5acc2a066f11eb8782ab347bdf11a0
    type: action
    subtype: rotate_right
    discovery_id: 0x00158d00042d6e36 action_rotate_right
  condition: []
  action:
  - type: brightness_increase
    device_id: a3ebeffb01be11ebaec2cbdc41234aa6
    entity_id: light.light_strip
    domain: light
  mode: single
- id: '1601922303700'
  alias: '[Office] Light strip toggle'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fb5acc2a066f11eb8782ab347bdf11a0
    type: action
    subtype: slide
    discovery_id: 0x00158d00042d6e36 action_slide
  condition: []
  action:
  - type: toggle
    device_id: a3ebeffb01be11ebaec2cbdc41234aa6
    entity_id: light.light_strip
    domain: light
  mode: single
- id: '1601922303793'
  alias: '[LOG] States'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.light_strip
    - light.56301471b4e62d5675cb
    - light.5058740184f3ebd05dfd
    - light.5058740184f3ebd0613c
    - light.big_balcony_light
    - binary_sensor.dressing_door_contact
    - binary_sensor.b_balcony_living_room_contact
    - binary_sensor.balcony_kitchen_door_contact
    - binary_sensor.bedroom_balcony_door_contact
    - binary_sensor.f_balcony_living_room_left_contact
    - binary_sensor.f_balcony_living_room_right_contact
    - vacuum.xiaomi_vacuum_cleaner
    - cover.05871234b4e62d79b938
    - cover.16236476a4cf12b18999
    - cover.61438062ecfabc68eee4
  condition: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: telegram_bot.send_message
    data:
      title: <b>{{ state_attr(trigger.entity_id, 'friendly_name') }}</b>
      message: <b>{{trigger.from_state.state.upper()}}</b> &#x27A1; <b>{{trigger.to_state.state.upper()}}</b>
      parse_mode: html
  mode: queued
  max: 10
- id: '1602438011912'
  alias: '[F Balcony] Light off'
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 23bc1f5e067a11ebbd86971d353d6d34
    entity_id: binary_sensor.f_balcony_living_room_right_contact
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: 0366831d068d11eb80b7cdda1350d8d3
    entity_id: binary_sensor.f_balcony_living_room_left_contact
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: 21030d46067411eba1f59ffc283f619a
    entity_id: binary_sensor.balcony_kitchen_door_contact
    domain: binary_sensor
  condition:
  - type: is_not_open
    condition: device
    device_id: 0366831d068d11eb80b7cdda1350d8d3
    entity_id: binary_sensor.f_balcony_living_room_left_contact
    domain: binary_sensor
  - type: is_not_open
    condition: device
    device_id: 23bc1f5e067a11ebbd86971d353d6d34
    entity_id: binary_sensor.f_balcony_living_room_right_contact
    domain: binary_sensor
  - type: is_not_open
    condition: device
    device_id: 21030d46067411eba1f59ffc283f619a
    entity_id: binary_sensor.balcony_kitchen_door_contact
    domain: binary_sensor
  action:
  - type: turn_off
    device_id: e2377ce908ce11ebbb0d5b7554271007
    entity_id: light.f_balcony_light
    domain: light
  mode: single
- id: '1602438663052'
  alias: '[F Balcony] Light on'
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 23bc1f5e067a11ebbd86971d353d6d34
    entity_id: binary_sensor.f_balcony_living_room_right_contact
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: 0366831d068d11eb80b7cdda1350d8d3
    entity_id: binary_sensor.f_balcony_living_room_left_contact
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: 21030d46067411eba1f59ffc283f619a
    entity_id: binary_sensor.balcony_kitchen_door_contact
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - type: turn_on
    device_id: e2377ce908ce11ebbb0d5b7554271007
    entity_id: light.f_balcony_light
    domain: light
  mode: single
