
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

meteo_france:
  - city: '06600'

vacuum:
  - platform: xiaomi_miio
    host: 10.0.4.126
    token: !secret vacuum_token
    
binary_sensor:
  - platform: workday
    country: FRA
    
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id