
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

meteo_france:
  - city: '06600'

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token
    
binary_sensor:
  - platform: workday
    country: FRA
    
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

lovelace:
  mode: yaml

influxdb:
  host: !secret influxdb_ip
  port: !secret influxdb_port
  database: homeassistant
  username: !secret influxdb_ha_user
  password: !secret influxdb_ha_pass
  max_retries: 3
  default_measurement: state